media:
  input: public/img
  output: /img
content:
  - name: stories
    label: Stories
    type: collection
    path: public/stories
    fields:
      - name: name
        type: string
      - name: role
        type: select
        options:
          values: ["Partnership", "Resident"]
      - name: neighborhood
        type: string
      - name: heroImage
        type: image
        options: 
          path: public/img
      - name: videoUrl
        type: string
      - name: coords
        type: string
      - name: body
        type: rich-text